# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('usrname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('profile_pic', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
