# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='useractive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=5)),
            ],
        ),
    ]
