# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0003_useractive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.FileField(max_length=150, upload_to=''),
        ),
    ]
